name: aws-nth-crossplane-resources
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/aws-nth-crossplane-resources
  tag: v0.0.1
  pullPolicy: IfNotPresent
