apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: {{.Values.clusterName}}-nth
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  providerConfigRef:
    name: {{.Values.clusterName}}
  forProvider:
    name: {{.Values.clusterName}}-nth
    tags:
      giantswarm.io/cluster: {{.Values.clusterName}}
      giantswarm.io/used-for: termination-handler
      sigs.k8s.io/cluster-api-provider-aws/cluster/{{.Values.clusterName}}: owned
    region: {{.Values.region}}
    messageRetentionSeconds: 300
  writeConnectionSecretToRef:
    name: {{.Values.clusterName}}-nth-sqs-connection
    namespace: {{ $.Release.Namespace }}
---
apiVersion: sqs.aws.upbound.io/v1beta1
kind: QueuePolicy
metadata:
  name: {{.Values.clusterName}}-nth
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  providerConfigRef:
    name: {{.Values.clusterName}}
  forProvider:
    region: {{.Values.region}}
    policy: |
      {
        "Version": "2012-10-17",
        "Id": "EC2InterruptionPolicy",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "events.amazonaws.com",
                "sqs.amazonaws.com"
              ]
            },
            "Action": "sqs:SendMessage",
            "Resource": "arn:{{.Values.awsPartition}}:sqs:{{.Values.region}}:{{.Values.accountID}}:{{.Values.clusterName}}-nth"
          }
        ]
      }
    queueUrlRef:
      name: {{.Values.clusterName}}-nth
